---

- name: Create a BigQuery Dataset
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_id: "openenv-g5wxq"
    dataset_id: "demo_dataset"
    table_id: "clientes"
  tasks:
    - name: Create a Google BigQuery Dataset
      register: create_dataset
      google.cloud.gcp_bigquery_dataset:
        name: "{{ dataset_id }}"
        dataset_reference:
          dataset_id: "{{ dataset_id }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        # service_account_file: "{{ _service_account_file_ }}"
        state: present
      tags:
        - dataset

    - name: Create a new table in BigQuery
      register: create_table
      google.cloud.gcp_bigquery_table:
        name: "{{ table_id }}"
        dataset: "{{ dataset_id }}"
        table_reference:
          dataset_id: "{{ dataset_id }}"
          project_id: "{{ project_id }}"
          table_id: "{{ table_id }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        # service_account_file: "{{ _service_account_file_ }}"
        state: present
        schema:
          fields:
            - name: id
              type: INTEGER
              mode: REQUIRED
            - name: nombre
              type: STRING
              mode: REQUIRED
            - name: email
              type: STRING
              mode: REQUIRED
      tags:
        - table

    # - name: Create new serviceaccount in Google Cloud
    #   register: sa
    #   google.cloud.gcp_iam_service_account:
    #     name: henry16@example.com-g5wxq.iam.gserviceaccount.com
    #     display_name: Ansible Service Account
    #     project: "{{ project_id }}"
    #     auth_kind: serviceaccount

    - name: Insert data into BigQuery table
      ansible.builtin.uri:
        url: "https://bigquery.googleapis.com/bigquery/v2/projects/{{ project_id }}/datasets/{{ dataset_id }}/tables/{{ table_id }}/insertAll"
        method: POST
        headers:
          Authorization: "Bearer {{ gcp_access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          rows:
            - json: {"id": 1, "nombre": "Juan Pérez", "email": "juan.perez@example.com"}
            - json: {"id": 2, "nombre": "Ana García", "email": "ana.garcia@example.com"}
            - json: {"id": 3, "nombre": "Luis Martínez", "email": "luis.martinez@example.com"}
            - json: {"id": 4, "nombre": "Carla Rodríguez", "email": "carla.rodriguez@example.com"}
            - json: {"id": 5, "nombre": "José López", "email": "jose.lopez@example.com"}
            - json: {"id": 6, "nombre": "Marta Sánchez", "email": "marta.sanchez@example.com"}
            - json: {"id": 7, "nombre": "David Fernández", "email": "david.fernandez@example.com"}
            - json: {"id": 8, "nombre": "Patricia González", "email": "patricia.gonzalez@example.com"}
            - json: {"id": 9, "nombre": "Francisco Pérez", "email": "francisco.perez@example.com"}
            - json: {"id": 10, "nombre": "Raquel Díaz", "email": "raquel.diaz@example.com"}
            - json: {"id": 11, "nombre": "Sergio García", "email": "sergio.garcia@example.com"}
            - json: {"id": 12, "nombre": "Lucía Romero", "email": "lucia.romero@example.com"}
            - json: {"id": 13, "nombre": "Javier Jiménez", "email": "javier.jimenez@example.com"}
            - json: {"id": 14, "nombre": "Pablo Ruiz", "email": "pablo.ruiz@example.com"}
            - json: {"id": 15, "nombre": "Elena Martínez", "email": "elena.martinez@example.com"}
            - json: {"id": 16, "nombre": "Carlos Gómez", "email": "carlos.gomez@example.com"}
            - json: {"id": 17, "nombre": "Isabel Herrera", "email": "isabel.herrera@example.com"}
            - json: {"id": 18, "nombre": "Manuel López", "email": "manuel.lopez@example.com"}
            - json: {"id": 19, "nombre": "Verónica Ortega", "email": "veronica.ortega@example.com"}
            - json: {"id": 20, "nombre": "Fernando Sánchez", "email": "fernando.sanchez@example.com"}
      tags:
        - data

    # - name: Crear una vista para el Dataset de BigQuery
    
    # - name: Asignar rol de BigQuery a un usuario
    #   google.cloud.gcp_iam_policy_binding:
    #     resource: "projects/{{ project_id }}"
    #     policy_bindings:
    #       - role: roles/bigquery.dataViewer
    #         members:
    #           - user:fegarcia@redhat.com
    #     auth_kind: serviceaccount
    #     # service_account_file: /path/to/service-account.json
    #     state: present
    #   tags:
    #     - iam

    - name: Asignar role para consulta al dataset
      ansible.builtin.uri:
        url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:setIamPolicy"
        method: POST
        headers:
          Authorization: "Bearer {{ gcp_access_token }}"
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "role": "roles/bigquery.dataViewer",
            "members": [
              "user:{{ user_email }}"
            ]
          }
      register: role_bind
      tags:
        - rolebind
