---
- name: Manage Rolebinding
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Synchronize repository
      ansible.builtin.include_role:
        name: demos.utils.git
      vars:
        git_operation: clone
        git_repository: https://github.com/zaskan/gcp-bigquery.git
        git_directory: /tmp/rolebinding

    - debug: msg="{{ lookup('ansible.builtin.file'. '/tmp/rolebinding/rolebinding.json') }}"
