---
- name: Manage Rolebinding
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Clone repository
      ansible.builtin.command: "git clone -b devel https://github.com/zaskan/gcp-bigquery.git"
      args:
        chdir: "/tmp/"

    - debug: msg="{{ lookup('ansible.builtin.file', '/tmp/gcp-bigquery/rolebinding.json') }}"
