---
- name: Manage Rolebinding
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Synchronize repository
      ansible.builtin.include_role:
        name: demos.utils.git
      vars:
        operation: clone
        repository: https://github.com/zaskan/gcp-bigquery.git
        directory: /tmp

    - debug: msg="{{ lookup('ansible.builtin.file'. '/tmp/rolebinding.json') }}"
