---
- name: Manage Rolebinding
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create git_directory
      ansible.builtin.file:
        path: /tmp/rolebinding
        state: directory

    - name: Synchronize repository
      ansible.builtin.include_role:
        name: demos.utils.git
      vars:
        git_operation: clone
        git_repository: https://github.com/zaskan/gcp-bigquery.git
        git_directory: /tmp/rolebinding
    
    - command: "find /tmp/rolebinding -name 'rolebinding.json'"
      register: file_out

    - debug: msg="{{ file_out }}"
   
    - debug: msg="{{ lookup('ansible.builtin.file', '/tmp/rolebinding/gcp-bigquery/rolebinding.json') }}"
