---
- name: Manage Rolebinding
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get current project IAM policy
      ansible.builtin.uri:
        url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:getIamPolicy"
        method: POST
        headers:
          Authorization: "Bearer {{ lookup('ansible.builtin.env', 'GOOGLE_OAUTH_ACCESS_TOKEN') }}"
          Content-Type: "application/json"
        return_content: true
      register: current_policy

    - name: Get current etag
      ansible.builtin.set_fact:
        etag: "{{ current_policy.content | from_json | community.general.json_query('etag') }}"

    - name: Clone repository
      ansible.builtin.command: "git clone -b devel https://github.com/zaskan/gcp-bigquery.git"
      args:
        chdir: "/tmp/"

    - name: Convert roles to dict
      ansible.builtin.set_fact:
        rolebinding: "{{ lookup('ansible.builtin.file', '/tmp/gcp-bigquery/rolebinding.json') | from_json }}"

    - name: Replace etag
      ansible.utils.update_fact:
        updates:
          - path: rolebinding.etag
            value: "{{ etag }}"
      register: new_rolebinding

    - name: Print
      ansible.builtin.debug:
        msg: "{{ new_rolebinding | to_json }}"

    - name: Update project IAM policy
      ansible.builtin.uri:
        url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:setIamPolicy"
        method: POST
        headers:
          Authorization: "Bearer {{ lookup('ansible.builtin.env', 'GOOGLE_OAUTH_ACCESS_TOKEN') }}"
          Content-Type: "application/json"
        body_format: json
        body:
          policy: "{{ new_rolebinding.policy | to_json }}"
        return_content: true
      register: update_result

