---
- name: Manage Rolebinding
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get current project IAM policy
      ansible.builtin.uri:
        url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:getIamPolicy"
        method: POST
        headers:
          Authorization: "Bearer {{ lookup('ansible.builtin.env', 'GOOGLE_OAUTH_ACCESS_TOKEN') }}"
          Content-Type: "application/json"
        return_content: true
      register: current_policy

    - debug: msg="{{ current_policy.content | from_json }}"

    - name: Clone repository
      ansible.builtin.command: "git clone -b devel https://github.com/zaskan/gcp-bigquery.git"
      args:
        chdir: "/tmp/"

    - name: Get contents of the file
      ansible.builtin.set_fact:
        rolebinding: "{{ lookup('ansible.builtin.file', '/tmp/gcp-bigquery/rolebinding.json') }}"

    - name: Update project IAM policy
      ansible.builtin.uri:
        url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:setIamPolicy"
        method: POST
        headers:
          Authorization: "Bearer {{ lookup('ansible.builtin.env', 'GOOGLE_OAUTH_ACCESS_TOKEN') }}"
          Content-Type: "application/json"
        body_format: json
        body:
          policy: "{{ rolebinding }}"
        return_content: true
      register: update_result

