---
# tasks file for big_query_caixa

- name: Create a Google BigQuery Dataset using Role
  ansible.builtin.include_tasks:
    file: dataset.yml
    apply:
      tags:
        - never
        - dataset

- name: Create a new table in BigQuery
  ansible.builtin.include_tasks:
    file: table.yml
    apply:
      tags:
        - never
        - table

- name: Insert data into BigQuery table
  ansible.builtin.include_tasks:
    file: insert.yml
    apply:
      tags:
        - never
        - data

- name: Create BigQuery View
  ansible.builtin.include_tasks:
    file: view.yml
    apply:
      tags:
        - never
        - view

- name: Asignar role para consulta al dataset
  ansible.builtin.include_tasks:
    file: role.yml
    apply:
      tags:
        - never
        - rolebind
