---
- name: Assign role to dataset
  ansible.builtin.uri:
    url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:setIamPolicy"
    method: POST
    headers:
      Authorization: "Bearer {{ lookup('ansible.builtin.env', 'GOOGLE_OAUTH_ACCESS_TOKEN') }}"
      Content-Type: "application/json"
    body_format: json
    body: "{{ lookup('ansible.builtin.url', policy_url, split_lines=False ) | from_json }}"
  register: role_bind
