---
- name: Assign role to dataset
  ansible.builtin.uri:
    url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:setIamPolicy"
    method: POST
    headers:
      Authorization: "Bearer {{ lookup('ansible.builtin.env', 'GOOGLE_OAUTH_ACCESS_TOKEN') }}"
      Content-Type: "application/json"
    body_format: json
    body: |
          {
            policy: {
              bindings: [
                {
                  "role": "roles/bigquery.{{ role }}",
                  "members": [
                    "user:{{ user_email }}"
                  ]
                }
              ]
            }
          }
  register: role_bind
