---
- name: Get current project IAM policy
  ansible.builtin.uri:
    url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:getIamPolicy"
    method: POST
    headers:
      Authorization: "Bearer {{ lookup('ansible.builtin.env', 'GOOGLE_OAUTH_ACCESS_TOKEN') }}"
      Content-Type: "application/json"
    return_content: true
  register: current_policy

- name: Merge in new binding
  ansible.builtin.set_fact:
    new_policy_json: >-
      {{
        current_policy.json |
        combine({
          "bindings": (current_policy.json.bindings + [
            {
              "role": "roles/"+role+"",
              "members": [
                ""+principal+":"+service_account_email+""
              ]
            }
          ])
        })
      }}

- name: Update project IAM policy
  ansible.builtin.uri:
    url: "https://cloudresourcemanager.googleapis.com/v1/projects/{{ project_id }}:setIamPolicy"
    method: POST
    headers:
      Authorization: "Bearer {{ lookup('ansible.builtin.env', 'GOOGLE_OAUTH_ACCESS_TOKEN') }}"
      Content-Type: "application/json"
    body_format: json
    body:
      policy: "{{ new_policy_json }}"
    return_content: true
  register: update_result
