---
- name: Listen for events on a Github webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Print event
      condition: event.payload.ref != "refs/heads/rolebinding"
      action:
        debug:
          msg: "Message 1 {{ event.payload.after }}"
